image: docker:latest

services:
  - mongo
  - redis

stages:
  - test-package
  - package


createVersionFile:
  stage: pre-package
  image: node:8
  script:
    - node _ci/create-version-file.js
  artifacts:
    paths:
      - VERSION
      - NAME
  only:
    - master

testVersion:
  stage: test-package
  services: 
    # dbs for testing
  script:
    - docker login -u $ACR_USER -p $ACR_PWD https://$ACR_HOST
    - sh _ci/increment-pre-version.sh
    - docker build -t $ACR_HOST/"$(cat NAME)":"$(cat VERSION)"-pre"$(cat PRE_VERSION)" .
    - docker push $ACR_HOST/"$(cat NAME)":"$(cat VERSION)"-pre"$(cat PRE_VERSION)"
  when: manual
  only:
    - pre-master

releaseVersion:
  stage: test-package
  services:
    # prod dbs
  script:
    - docker login -u $ACR_USER -p $ACR_PWD https://$ACR_HOST
    - docker build -t $ACR_HOST/"$(cat NAME)":"$(cat VERSION)" .
    - docker push $ACR_HOST/"$(cat NAME)":"$(cat VERSION)"
  when: manual
  only:
    - master


